name: Build Hugo Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set write permission for the GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically provided by GitHub
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true  # Creates a new history for the gh-pages branch
          
      - name: Trigger workflow in nix-config repo
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/footvaalvica/nix-config/dispatches \
          -d '{"event_type": "website-update", "client_payload": {"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}}'
